### PR TITLE
Refactored `extern`, `use`, and `mod` statements to 2018 edition of Rust

### PR DESCRIPTION
**Pull request by akhilles**
Only updated 3 crates for now: `sgx_alloc`, `sgx_trts`, and `sgx_types`.

Also, `include` key is not needed in `Cargo.toml` because Cargo defaults to use `.gitignore`.

### CODE REVIEW

**Comment by akhilles** [comment]
Partially addresses  #136

**Comment by dingelish** [comment]
Thanks Akhil! I'm looking into this!

**Comment by dingelish** [comment]
hmmmm I prefer still using `include` because I think `.gitignore` should not be responsible for "including everything that cannot be packaged in".

I think the better choice is to "keep the behavior of `cargo package` reproducible` without external `.gitignore`. Is this a good choice? Appreciate your comments!

**Comment by akhilles** [comment]
> keep the behavior of `cargo package` reproducible without external `.gitignore`

Definitely agree with this. But maybe it makes sense use `exclude` fields (when needed) instead (https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields-optional)? I only made this change because there was an issue where a new file was added in a commit but the `include` list wasn't updated. This led to the crate compiling when added as a git dependency but it didn't compile when it was added as a `crates.io` dependency.

**Comment by dingelish** [comment]
Good! You're right. Let's use `exclude`!

**Pull request merged**
