### PR TITLE
sgx_tstd bazel target and it's dependencies

### PR DESCRIPTION
**Pull request by ghost**
More crates have been ported to bazel including the `sgx_tstd` crate in pursuit of #52 . Also the `libbacktrace` has been ported to bazel and compiled successfully. 

The `sgx_unwind` has been linked only with `gcc_s` for now.
The `sgx_tstd` only default feature `stdio` has been enabled.

### CODE REVIEW

**Comment by ghost** [comment]
Please review the changes. I will try to port some samplecode to use bazel as well, to be able to test that rules work using bazel. Will introduce the sgx rules from google repo as well.

**Comment by dingelish** [comment]
Thanks sooooooo much bro! But recently I'm gonna push v1.0.9, and I removed the libbacktrace, and added libunwind in sgx_unwind. Of course your previous merged works are included. Could I push my commits first? Sorry for the inconvenience!

**Comment by ghost** [comment]
Hey @dingelish, will have a look tomorrow. Shouldn't matter much. Will pull and change the commits.

**Comment by tomtau** [comment]
@Sythanis awesome work!

BTW, for `sgx_tstd`, the default Bazel Rust rules don't use Cargo, right? One thing I'm thinking is whether it'd be possible to build Rust SGX SDK projects using a stable version of rustc using Bazel -- currently, this is only possible using Xargo @dingelish ? https://github.com/japaric/xargo#std

**Comment by ghost** [comment]
@dingelish  please feel free to merge 1.0.9 to master. Will refactor the application.

@tomtau, currently having a look at this. I might have to write some custom bazel rules for this, need to see what Rules Rust export out. 

I will try to get sample applications working and the see.

**Comment by ghost** [comment]
I will be creating  new longer lasting branch here that will make my commint managment better. What do you say if we create a bazel branch on main repo as well, which will mirror mine bazel branch. Thus I can release to main, but we can say that bazel is still very unstable

**Comment by ghost** [comment]
I have created an issue in `rules_rust` as xargo functionality replacement in `rules_rust` might be a bit beyond me still. For the reference https://github.com/bazelbuild/rules_rust/issues/250

**Comment by dingelish** [comment]
mistakenly closed ... please create a PR again. I'm really sorry.

**Pull request closed without merging**
