### PR TITLE
db-proxy(VeritasDB) on rust-sgx-sdk

### PR DESCRIPTION
**Pull request by bradyjoestar**
#116 
This is a code implementation of VeritasDB on rust-sgx-sdk.
It will guarantee on database integrity verification and database privacy.

I will continue focusing on it. :smile:

### CODE REVIEW

**Comment by bradyjoestar** [comment]
Although there are some things need to be done, I think this pr could be merged if you agree with it. :smile:

Performance Optimizations should be considerd in the paper so I will take some time on it.
@dingelish

**Comment by dingelish** [comment]
Sure! Thank you so much for your contribution!

**Comment by davidp94** [comment]
Wow nice one ! Thanks

**Comment by bradyjoestar** [comment]
@davidp94 This is a simple implement for go and I will translate it to rust.
more work is on the way! :beers:

**Comment by dingelish** [comment]
@bradyjoestar Do you have a plan to finish it? I really like it!

**Comment by bradyjoestar** [comment]
@dingelish Sorry I am recently busy working on sqlite in the sgx at the production enviroment :-)

I couldn't assure when this pr is completed. :smile:

**Pull request merged**
