### PR TITLE
fix sgx_urts  undefined reference to `t_signal_handler_ecall` error

### PR DESCRIPTION
**Pull request by volcano0dr**
Use signal feature to control compilation of sgx_urts::signal. #234

### CODE REVIEW

**Comment by assafmo** [comment]
How can I use this with v1.1.2?

**Comment by mssun** [comment]
@assafmo, you can use it right now with the v1.1.2 tag. I believe @dingelish re-taged the v1.1.2 to the current master.

BTW, I think it's better to come up with a better tagging/versioning strategy. I'll bring up this issue later.

**Comment by assafmo** [comment]
Yeah you probably don't want to re-tag refs. Just tag it as v1.1.3 and say on the changelog that it's a bug fix.

**Comment by mssun** [comment]
@assafmo It is not just simple do a version bump. You have to bump all versions also for ported crates. Otherwise, you will see multiple std when using cargo. I have created a mono repo for SGX crates and have a details versioning instructions (https://github.com/universal-secure-computing-community/crates-sgx). Once this is ready, version bump for SDK will be very easy and there is minimal effort to update all ported SGX crates.

**Pull request merged**
