### PR TITLE
Upgrade to 1.55 nightly

### LINKED ISSUE #315: Support stable rust?
Why nightly rust is needed? Using nightly rust has several major disadvantages:

* Need to be constantly updated to keep sync with upstream. Currently, the pinned nightly version (1.49.0 nightly-2020-10-25) is already lagged behind the current stable rust (1.49.0 2020-12-29).
* Nightly rust is of course not stable and may be error prone.

Can stable rust be supported, specially if the enclave code is written in `no_std`?

### PR DESCRIPTION
**Pull request by celaus**
Hi! We needed to use a compiler > 1.50 for adding new dependencies that rely on const generics. Since `std::raw` has been removed in current nightly versions (and it's not entirely clear to me where it's used in the SGX SDK) this compiler upgrade should be safe to make. All the sample code compiles and I could manually run several of them inside the 18.04 container. 

For anyone also using 3rd party ports of libraries to this SGX SDK (because they won't build with the new compiler version out of the box), use this in your `Cargo.toml` (upgrade later to this - official - repo):

~~~toml
[patch.'https://github.com/apache/teaclave-sgx-sdk.git']
sgx_align_struct_attribute = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_alloc = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_backtrace = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_backtrace_sys = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_build_helper = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_cov = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_crypto_helper = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_demangle = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_libc = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_no_tstd = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_rand = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_rand_derive = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_serialize = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_serialize_derive = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_serialize_derive_internals = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_tcrypto = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_tcrypto_helper = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_tdh = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_tkey_exchange = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_tprotected_fs = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_trts = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_tse = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_tseal = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_tstd = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_tunittest = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_types = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_ucrypto = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_unwind = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
sgx_urts = { git = "https://github.com/celaus/incubator-teaclave-sgx-sdk" }
~~~

Don't forget to `cargo update`

Somewhat fixes #315

### CODE REVIEW

**Comment by xu-cheng** [comment]
@volcano0dr @dingelish Any chance to merge this?

**Comment by volcano0dr** [comment]
@celaus @xu-cheng 
I plan to upgrade the rust toolchain on the `v1.1.4-testing` branch soon.

**Comment by xu-cheng** [comment]
Hi, sorry to ping again. But any chance to move this forward?

Noted that Rust 2021 edition is about to be stabilize in Rust 1.56, which will be in beta in a week. We should really upgrade the support rust version of this SDK. Otherwise, it is likely that many crates will stop compiling if they are upgrading to 2021 edition.

**Comment by mssun** [comment]
I think this should be properly resolved as soon as possible.

@volcano0dr any timeline for the new version?

**Comment by PiDelport** [comment]
The `v1.1.4-testing` branch was merged, with toolchain `nightly-2021-09-13` (rustc 1.57.0-nightly).

- See: #360

**Pull request closed without merging**
