### PR TITLE
Fixed Spelling.

### PR DESCRIPTION
**Pull request by jimmycasey**

### CODE REVIEW

**Comment by dingelish** [comment]
Thanks @jimmycasey ! I think you can submit a PR to the original [rust-crypto](https://github.com/DaGenix/rust-crypto/blob/cc1a5fde1ce957bd1a8a2e30169443cdb4780111/src/aessafe.rs#L10) as well!

**Comment by davidp94** [comment]
by checking @jimmycasey profile, it looks like a bot that crawl all famous repos and create PR automatically :)

**Comment by dingelish** [comment]
Interesting! I like this idea!

**Comment by jimmycasey** [comment]
Hey folks,
I left the creating of the PR bit manual in case it was nonsense.
The bot has created 838 forks and commits tho :)

**Pull request merged**
